fix problem that gulp serve is not working
```
% $(npm bin)/gulp serve                                               {satoshi[@]satoshinoMacBook-Pro.local}
fs.js:40
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/Users/satoshi/Desktop/eisenscript-editor/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/satoshi/Desktop/eisenscript-editor/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/satoshi/Desktop/eisenscript-editor/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
```